version: "3.7"

services:
  torchbench_cuda:
    user: root
    build: ./docker
    image: torchbench:latest
    cap_add:
      - SYS_ADMIN
    command: nsys profile -t cublas,cuda,cudnn,nvtx,openacc,osrt --cuda-memory-usage true -o /workspace/benchmark/ncu_reports/resnet50-nsystems --force-overwrite true python run.py resnet50 -d cuda -m eager -t eval --profile
    working_dir: /workspace/benchmark
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

    volumes:
      - ${HOME}/ncu_reports:/workspace/benchmark/ncu_reports
  # torchbench_cpu:
  #   image: torchbench:latest
  #   command: python run.py resnet50 -d cpu -m eager -t eval --profile
  #   working_dir: /workspace/benchmark
  

