version: "3.7"

services:
  torchbench_cuda:
    build: ./docker
    image: torchbench:latest
    command: python run.py resnet50 -d cuda -m eager -t eval --profile
    working_dir: /workspace/benchmark
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

  # torchbench_cpu:
  #   image: torchbench:latest
  #   command: python run.py resnet50 -d cpu -m eager -t eval --profile
  #   working_dir: /workspace/benchmark
